AllCops:
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
    - Gemfile

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Rails/DynamicFindBy:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/CommandLiteral:
  EnforcedStyle: mixed

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal
